feat: move commands to sf style
salesforcecli/plugin-schema pull request #325
Opened 2022-11-16 17:47 UTC by cristiand391

### What does this PR do?

### What issues does this PR fix or reference?
@W-11595970@

2022-12-15 22:24 UTC, WillieRuemmele commented on .eslintrc.js
> +  extends: ['eslint-config-salesforce-typescript', 'eslint-config-salesforce-license', 'plugin:sf-plugin/recommended'],
is this to be committed, or only a dev-time change?

2022-12-19 21:28 UTC, peternhale requested changes

2022-12-19 21:28 UTC, peternhale commented on src/commands/sobject/describe.ts
> +      CliUx.ux.styledJSON(description);
@cristiand391 should use this.styledJson and should have to guard the call. That is done inside this.styledJson.

2022-12-19 21:28 UTC, peternhale commented on src/commands/sobject/list.ts
> +    }
``` suggestion
    if (!sobjects.length)
      this.log(messages.getMessage('noTypeFound', [SObjectType[type]]));
    }
```

2022-12-19 21:28 UTC, peternhale commented on src/commands/sobject/list.ts
> +    let havePrinted = false;
remove this var in conjunction with suggestion below

2022-12-19 21:50 UTC, peternhale requested changes

2023-01-02 17:28 UTC, cristiand391 commented on .eslintrc.js
> +  extends: ['eslint-config-salesforce-typescript', 'eslint-config-salesforce-license', 'plugin:sf-plugin/recommended'],
this needs to be commited in the eslint config file, I think `migration` is the one to be used at dev-time only
https://github.com/salesforcecli/eslint-plugin-sf-plugin#use-these-rules-to-migrate-a-plugin-based-on-sfdxcommand-to-use-sfcommand

2023-01-03 12:55 UTC, peternhale requested changes

2023-01-03 12:55 UTC, peternhale commented on src/commands/sobject/describe.ts
> +  public static readonly summary = messages.getMessage('summary');
@cristiand391 Each of the commands should have aliases for the `force` command name for backward compatibility

2023-01-03 12:55 UTC, peternhale commented on src/commands/sobject/list.ts
> +  public static readonly summary = messages.getMessage('summary');
add alias to `force:sobject:list`

2023-01-03 13:36 UTC, cristiand391 commented on src/commands/sobject/describe.ts
> +  public static readonly summary = messages.getMessage('summary');
Yep, it's defined here:
https://github.com/salesforcecli/plugin-schema/pull/325/files#diff-934970c353339c1496544b20307098358e2b81e0ece373314644386bff390718R26

2023-01-03 13:36 UTC, cristiand391 commented on src/commands/sobject/describe.ts
> +  public static readonly summary = messages.getMessage('summary');
Yep, it's defined here:
https://github.com/salesforcecli/plugin-schema/pull/325/files#diff-934970c353339c1496544b20307098358e2b81e0ece373314644386bff390718R26

2023-01-03 13:37 UTC, cristiand391 commented on src/commands/sobject/list.ts
> +  public static readonly summary = messages.getMessage('summary');
`force:schema:sobject:list` alias:
https://github.com/salesforcecli/plugin-schema/pull/325/files#diff-32f2d42898880e5f6b65caf624dc0c7de6f4d1d0d4dd937283e5869dbe17d5c7R32

2023-01-03 13:40 UTC, peternhale approved these changes

2023-01-03 13:51 UTC, peternhale commented
@cristiand391 have you had a look at the windows unit test failures?

2023-01-03 14:53 UTC, cristiand391 commented
@peternhale fixed ✅

2023-01-04 16:38 UTC, WillieRuemmele approved these changes

2023-01-04 17:02 UTC, cristiand391 commented on src/commands/sobject/describe.ts
> +      aliases: ['usetoolingapi', 't'],
Good catch. I moved it to `char`, that way it will show up in the command help text too (flag aliases aren't printed).

2023-01-04 17:08 UTC, WillieRuemmele commented
### QA Notes
---
`schema:sobject:describe`

❌ : `-h` not working for either command
```
 ➜  ../../oss/plugin-schema/bin/dev force:schema:sobject:describe -h         
Error: Unexpected argument: -h
See more help with --help
```
✅ : `--help`
✅ : `Error: The requested resource does not exist` matches
✅ : `force:schema:sobject:describe --sobjecttype Account`
✅ : `-t`, `--use-tooling-api`, `--usetoolingapi`
✅ : `--json`
❓ : removed the `--loglevel` flag

---

`schema:sobject:list`

❌ : `-h` not working
✅ : `--json`
✅ : human output
❓ : `--loglevel` removed
✅ : `-c`, `-s`, `--sobjecttypecategory`, `--sobject` interop
❌ : `CUSTom` works with old, not with new
```
 ➜  ../../oss/plugin-schema/bin/dev force:schema:sobject:list --sobjecttypecategory CUSTOm
Error: Expected --sobject=CUSTOm to be one of: all, standard, custom, ALL, STANDARD, CUSTOM
See more help with --help
➜  dreamhouse-lwc git:(main) ✗  hub:(GLOBAL - DevHub) scratch:(test-gl6bfhfilxof@example.com)
 ➜  sfdx force:schema:sobject:list --sobjecttypecategory CUSTom
Broker__c
Property__c
intrelorgnsna40__MyCustomObject__c
```

2023-01-04 19:56 UTC, peternhale approved these changes

2023-01-04 20:14 UTC, WillieRuemmele commented
### QA Notes
---
✅ : can now `../../oss/plugin-schema/bin/dev force:schema:sobject:list --sobject CUSTom`
✅ : `-h` for both commands works when linked into a CLI
```
 ➜  ../../oss/sfdx-cli/bin/run force:schema:sobject:describe -h
Display the metadata for a standard or custom object or a Tooling API object.

USAGE
  $ sfdx sobject describe -s <value> [--json] [-o <value>] [--api-version <value>] [-t]

FLAGS
  -o, --target-org=<value>  [default: test-gl6bfhfilxof@example.com] Username or alias of the target org.
  -s, --sobject=<value>     (required) API name of the object to describe.
  -t, --use-tooling-api     Use Tooling API to display metadata for Tooling API objects.
  --api-version=<value>     Override the api version used for api requests made by this command

GLOBAL FLAGS
  --json  Format output as json.
```
✅ : `sfdx sobject list`
✅ : `sfdx sobject describe`

2023-01-04 20:14 UTC, merged